### ISSUE TITLE
STM32F2 support

### ISSUE THREAD

**Issue by temporaryaccount** [ChibiOS/ChibiOS#3]
[This page](http://www.chibios.org/dokuwiki/doku.php?id=chibios:matrix) claims STM32F2xx support but I couldn't find the library files inside ChibiOS directory tree. The os/hal/ports/STM32 contains directories for F0, F1, F3, F4, L1 but not for F2, F7 and L0 (from current series).

**Comment by barthess** [comment]
If I remember correctly F2 support was merged into F4 code. Please post your future questions here http://forum.chibios.org/phpbb/index.php
